@startuml
'https://plantuml.com/sequence-diagram

!include style.puml


box Logic LOGIC_COLOR_T1
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant "<<Class>>\nParser" as Parser LOGIC_COLOR
end box

[-> AddCommand : execute
activate AddCommand
AddCommand -> Parser++: getArgumentsCount((argumentList: String[]):
return slashesCount: int
AddCommand -> Parser++: getClassType(argumentList: String[])
return addType: String
AddCommand -> Parser++: getClassType(argumentList: String[])
return addType: String

alt food
    ref over AddCommand: addFood
else strength
    ref over AddCommand: addStrengthExercise
else cardio

else weight
    ref over AddCommand: addWeightAndFat
else invalidType
    ref over AddCommand: handleInvalidAddType
end
return
destroy AddCommand
@enduml
