@startuml
'https://plantuml.com/sequence-diagram

autoactivate on

'Duke -> ui: input()
'User --> ui: user input
'Duke <-- ui: user input


-> addCommand: execute()
addCommand -> parser: getArgumentList(arguments: String)
return argumentList: String[]
addCommand -> parser: getClassType(argumentList: String[])
return addType: String

alt food
    ref over addCommand: addFood
else strength
    ref over addCommand: addStrengthExercise
else cardio

else weight
    ref over addCommand: addWeightAndFat

end

@enduml
