@startuml
'https://plantuml.com/sequence-diagram

!include style.puml
box Logic LOGIC_COLOR_T1
participant ":Duke" as Duke
participant ":AddCommand" as AddCommand LOGIC_COLOR
participant "<<Class>>\nParser" as Parser LOGIC_COLOR
participant ":WeightAndFatList" as WeightAndFatList LOGIC_COLOR

autoactivate on


activate addCommand
group addWeightAndFat
    addCommand -> addCommand: addWeightAndFat(argumentList: String[])
    opt date provided
        addCommand -> Parser: parseDate(date: String)
        return date: LocalDate
    end
    addCommand -> weightAndFat **: new
    activate weightAndFat
    addCommand <-- weightAndFat: weightAndFat: WeightAndFat
    addCommand -> weightAndFatList: addWeightAndFat(weightAndFat: WeightAndFat)
    return
    opt display
        addCommand -> weightAndFat: toString()
        return weightAndFatString: String
        addCommand -> ui: output(weightAndFatString: String)
        return
        addCommand -> ui: output(successMessage: String)
        return
    end

return

end

deactivate addCommand

@enduml