@startuml
!include style.puml

autoActivate on

box Logic LOGIC_COLOR_T1
participant ":FindCommand" as findCommand LOGIC_COLOR
participant "<<class>>\nParser" as parser LOGIC_COLOR
end box

[-> findCommand: execute()
findCommand -> parser: getArgumentList(arguments: String)
return argumentList: String[]

findCommand -> parser: getClassType(argumentList: String[])
return findType: String

alt food

else strength

else cardio

else date_f

else calories

else invalid findType

end
return

destroy findCommand
@enduml