@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":FindCommand" as FindCommand LOGIC_COLOR
participant "<<class>>\nParser" as Parser LOGIC_COLOR
end box

[-> FindCommand: execute()
activate FindCommand
FindCommand -> Parser++: getArgumentsCount(arguments: String)
return slashesCount: int

FindCommand -> Parser++: getArgumentList(arguments: String)
return argumentList: String[]

FindCommand -> Parser++: getClassType(argumentList: String[])
return findType: String

alt food
    ref over FindCommand: FindFood
else strength
    ref over FindCommand: FindStrengthExercise
else cardio
    ref over FindCommand: FindCardioExercise
else calories
    ref over FindCommand: FindCalories
else invalidType
    ref over FindCommand: handleInvalidFindType
end
return

FindCommand -[hidden]-> Parser

destroy FindCommand
@enduml