
@startuml
'https://plantuml.com/sequence-diagram

autoactivate on



Duke -> findCommand: execute()
findCommand -> parser: getArgumentList(arguments: String)
return argumentList: String[]
findCommand -> parser: getClassType(argumentList: String[])
return findType: String

alt

else strength

else cardio

else date_f

else calories

else invalid findType

end

@enduml