@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class HelpCommand {
    <u>+ COMMAND_DESCRIPTION: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_WORD: String
    <u>+ HEADING_INDENT: int
    <u>+ MESSAGE_COMMAND: String
    <u>+ MESSAGE_FORMAT_NOTE: String
    <u>+ MESSAGE_USAGE: String
    <u>+ MESSAGE_USER_GUIDE_REFERENCE: String
    <u>+ USER_GUIDE_LINK: String

    + HelpCommand(input String[])
    - formatCommandDescription(keyword: String, description: String): String
    - getAllCommandDescriptions(): ArrayList<String>
    - getAllCommandUsage(): ArrayList<String>
}

@enduml