@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class InfoCommand {
    - module: Module
    <u>+ COMMAND_DESCRIPTION: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_WORD: String
    <u>- DESCRIPTION_INDENTATION: String
    <u>- DESCRIPTION_SIZE: int
    <u>- HEADING_LENGTH: int
    <u>+ MISSING_MODULE_CODE: String
    <u>+ MODULE_NOT_FOUND: String

    + InfoCommand(input: String[])
    - addLine(ui: Ui, heading: String, details: String)
    - splitLongDescription(longDescription: String): String
}

@enduml