@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class InfoCommand {
    <u>+ COMMAND_DESCRIPTION: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_WORD: String
    <u>- DESCRIPTION_INDENTATION: String
    <u>- DESCRIPTION_SIZE: int
    <u>- HEADING_LENGTH: int
    <u>+ MISSING_MODULE_CODE: String
    - module: Module
    <u>+ MODULE_NOT_FOUND: String

    - addLine(Ui, String, String)
    - splitLongDescription(String): String
}

@enduml