@startuml
'https://plantuml.com/sequence-diagram
hide circle
skinparam classAttributeIconSize 0

class Link {
    <u>- DELIMITER: String
    <u>- DOMAIN: String
    <u>- LESSON_DELIMITER: String
    <u>- LESSON_TYPE_DELIMITER: String
    <u>- LINK_EXAMPLE: String
    <u>- LINK_PROCESS_ERROR_MESSAGE: String
    <u>- MODULE_DELIMITER: String
    <u>- MODULE_CODE_DELIMITER: String
    <u>- MODULES_PARAM_INDEX: int
    <u>- SEMESTER_DELIMITER: String
    <u>- SEMESTER_PARAM_INDEX: int
    <u>- SEMESTER_PROCESS_ERROR_MESSAGE: String
    <u>- SHARE_DELIMITER: String
    <u>- SUPPOSED_PREFIX: String
    <u>- SUPPOSED_PREFIX_REGEX: String
    <u>- POSSIBLE_SEMESTER_NUMBER: String

    <u>- addLessons(String[], SelectedModule, int): void
    <u>- addValidLesson(SelectedModule, int, LessonType, String): void
    <u>- appendModules(List<SelectedModule>, StringBuilder): void
    <u>+ getLessonType(String): LessonType
    <u>+ getLink(State): String
    <u>- getSemesterFromParam(String): int
    <u>- isEmptyLink(String): boolean
    <u>- isLessonInfo(String): boolean
    <u>- isValidPreviousState(String): boolean
    <u>- joinLessons(Map<LessonType, String>): String
    <u>+ parseLink(String, State): void
}
@enduml