@startuml
'https://plantuml.com/sequence-diagram
hide circle
skinparam classAttributeIconSize 0

class Link {
    <u>- DELIMITER: String
    <u>- DELIMITER_REGEX: String
    <u>- DOMAIN: String
    <u>- LESSON_DELIMITER: String
    <u>- LESSON_TYPE_DELIMITER: String
    <u>- LINK_EXAMPLE: String
    <u>- LINK_PROCESS_ERROR_MESSAGE: String
    <u>- MODULE_DELIMITER: String
    <u>- MODULE_CODE_DELIMITER: String
    <u>- MODULES_PARAM_INDEX: int
    <u>- SEMESTER_DELIMITER: String
    <u>- SEMESTER_PARAM_INDEX: int
    <u>- SEMESTER_PROCESS_ERROR_MESSAGE: String
    <u>- SHARE_DELIMITER: String
    <u>- SPECIAL_TERM_1_SEMESTER_DELIMITER: String
    <u>- SPECIAL_TERM_2_SEMESTER_DELIMITER: String
    <u>- SUPPOSED_PREFIX_REGEX: String

    <u>- addLessons(String[], SelectedModule, int, Ui)
    <u>- addValidLesson(SelectedModule, int, LessonType, String, Ui)
    <u>- appendModules(List<SelectedModule>, StringBuilder)
    <u>- appendSemester(State, StringBuilder)
    <u>- extractModulesAndLessons(Ui, int, String[], List<SelectedModule>)
    <u>- extractSemester(State, Ui, String[]): int
    <u>+ getLessonType(String, Ui): LessonType
    <u>+ getLink(State): String
    <u>- getSemesterFromParam(String): int
    <u>- isEmptyLink(String): boolean
    <u>- isLessonInfo(String): boolean
    <u>- isValidLink(String): boolean
    <u>- isValidPreviousState(String): boolean
    <u>- joinLessons(Map<LessonType, String>): String
    <u>+ parseLink(String, State, Ui)
}
@enduml