@startuml
'https://plantuml.com/sequence-diagram
hide circle
skinparam classAttributeIconSize 0

class Link {
    <u>- DOMAIN: String
    <u>- DELIMITER: String
    <u>- SEMESTER_DELIMITER: String
    <u>- SHARE_DELIMITER: String
    <u>- LESSON_TYPE_DELIMITER: String
    <u>- MODULE_CODE_DELIMITER: String
    <u>- POSSIBLE_SEMESTER_NUMBER: String
    <u>- SUPPOSED_PREFIX: String
    <u>- SUPPOSED_START_REGEX: String
    <u>- moduleDelimiter: String
    <u>- lessonDelimiter: String
    <u>- SEMESTER_PARAM_INDEX: int
    <u>- MODULES_PARAM_INDEX: int
    <u>- LINK_EXAMPLE: String
    <u>- LINK_PROCESS_ERROR_MESSAGE: String

    <u>+ parseLink(State, Ui): void
    <u>- getSemesterFromParam(String): int
    <u>- isValidPreviousState(String): boolean
    <u>- addLessons(String[], SelectedModule, int): void
    <u>- addValidLesson(SelectedModule, int, LessonType, String): void
    <u>- isLessonInfo(String): boolean
    <u>+ getLessonType(String): LessonType
    <u>+ getLink(State, Ui): String
    <u>- appendModules(List<SelectedModule>, StringBuilder): void
    <u>- appendLessons(Map<LessonType, String>, StringBuilder): void
}
@enduml