@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class ListCommand {
    - successful: boolean
    <u>+ COMMAND_DESCRIPTION: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_WORD: String
    <u>+ DETAILS_INDENT: int
    <u>+ HEADING_LENGTH: int

    + ListCommand(input: String[])
    + formatSelectedModule(module: SelectedModule, semester: int): String
    + formatSelectedSlots(module: Module, map: Map<LessonType, String>, semester: int): String
    - formatSingleSlot(module: Module, type: LessonType, classNo: String, semester: int): String
    - formatWeeks(weeks: List<Integer>): String
}

@enduml