@startuml
'https://plantuml.com/sequence-diagram

-> MarkCommand++:execute()
MarkCommand -> MarkCommand++:markExercise(argumentList: String[])
alt done
MarkCommand -> Calculator++:calculateExerciseCalories(biometrics: Biometrics, time: double, met: double)
return calories: int
MarkCommand -> ExerciseList++:markDone(index: int, time: double, calories: int)
return
MarkCommand -> Ui++:output(markDoneMessage: String)
return
else undone
MarkCommand -> ExerciseList++:markUndone(index: int)
return
MarkCommand -> Ui++:output(markUnDoneMessage: String)
return
end

@enduml