@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class Parser {
    <u>- ERROR_EMPTY_INPUT: String

    <u>+ parse(userInput: String): Command
    <u>- isEmptyInput(command: String): boolean
    <u>+ isModuleCode(moduleCode: String): boolean
    <u>+ isMultiWordsCommand(keywords: String[]): boolean
    <u>+ isOneWordCommand(keywords: String[]): boolean
    <u>+ isTwoWordsCommand(keywords: String[]): boolean
    <u>+ isValidSemester(keywords: String[]): boolean
    <u>+ isValidSpecialTerm(keywords: String[]): boolean
    <u>+ isValidTwoWordCommand(keywords: String[]): boolean
    <u>+ moduleRelatedCommandError(keywords: String[], initialErrorMessage: String)
    <u>+ parseParams(description: String): Map<String, String>
    <u>+ singleWordCommandError(keywords: String[])
}
@enduml