@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class RemoveModuleCommand {
    <u>+ COMMAND_DESCRIPTION: String
    <u>+ COMMAND_USAGE: String
    <u>+ COMMAND_WORD: String
    <u>- ERROR_WRONG_FORMAT: String
    - module: Module
    - successful: boolean
}

@enduml