@startuml
skinparam classAttributeIconSize 0
hide circle
class SearchModuleCommand {
 -toSearchModuleCode: String
 -toSearchModuleTitle: String
 -toSearchModuleLevel: String
 -toSearchModuleSemester: String
 -params: Map <String, String>
 -processParams() : void
 +addLineisSameModuleLevel() : boolean
 +isOfferedInSemester() : boolean
 +filterModuleSearch() : boolean

}
@enduml