@startuml
'https://plantuml.com/sequence-diagram
hide circle
skinparam classAttributeIconSize 0

class Storage {
    <u>+ FILE_PATH: String
    <u>+ NO_PREVIOUS_STATE_ERROR_MESSAGE: String
    <u>+ LOADING_PREVIOUS_STATE_MESSAGE: String
    <u>+ EXPORT_MESSAGE: String
    - logger: Logger
    <u>+ SUBSYSTEM_NAME: String

    + openPreviousState(State, Ui): void
    - readPreviousState(): String
    + saveState(State, Ui): void
}
@enduml