@startuml
'https://plantuml.com/class-diagram
hide circle
skinparam classAttributeIconSize 0

class Storage {
    - logger: Logger
    <u>+ EXPORT_MESSAGE: String
    <u>+ FILE_PATH: String
    <u>+ LOADING_PREVIOUS_STATE_MESSAGE: String
    <u>+ NO_PREVIOUS_STATE_ERROR_MESSAGE: String
    <u>+ SUBSYSTEM_NAME: String

    + openPreviousState(state: State, ui: Ui)
    - readPreviousState(): ArrayList<String>
    + saveState(state: State, ui: Ui, isExit: boolean)
}
@enduml