@startuml
'https://plantuml.com/class-diagram

abstract class Command {
{abstract} +execute(): void
{abstract} +setData(ui: Ui, storage: Storage, biometrics: Biometrics,
exerciseList: ExerciseList, foodList: FoodList): void
}

class ExerciseList {
-currentExerciseList: ArrayList<Exercise>
-completedExerciseList: ArrayList<Exercise>
+addExercise(exercise: Exercise): void
+getCurrentExercise(index: int): Exercise
+getCompletedExercise(index: int): Exercise
+getCurrentExerciseList(): ArrayList
+getCompletedExerciseList(): ArrayList
+getCurrentExerciseListSize(): int
+getCompletedExerciseListSize(): int
+markDone(index: int): void
+markUndone(index: int)): void
}

class Exercise {
-exerciseName: String
-repetition: int
-caloriesBurnt: int
-isDone: boolean
+getExerciseName(): int
+getRepetition(): int
+getCaloriesBurnt(): int
+getDone(): boolean
+getSet(): int
+getTaskStatus(): String
+getTaskStatusInNumber(): int
+setDone(isDone: boolean): void
+toString(): String
+saveExercise(): String
}

class StrengthExercise {
-set: int
}

class CardioExercise{
-time: int
}

class AddCommand {
-arguments: String;
-toDisplay: boolean
-isMarkDone: boolean
+execute(): void
-addStrengthExercise(argumentList: String[])): void
}

class ViewCommand {
-arguments: String
+execute(): void
-viewExercise(argumentList: String[]): void
-viewStrengthExercise(argumentList: String[]): void
}

class FindCommand {
-arguments: String
+execute(): void
-findStrength(argumentList: String[]): void
}

class RemoveCommand {
-arguments: String
+execute(): void
-removeExercise(argumentList: String[]): void
}

class MarkCommand {
-(argumentList: String[])
+execute(): void
+markExercise((argumentList: String[])
}

Duke --> "1"ExerciseList
Duke --> "*"Command
Command <|-- AddCommand
Command <|-- MarkCommand
Command <|-- ViewCommand
Command <|-- RemoveCommand
Command <|-- FindCommand
ExerciseList "1" o--> "*"Exercise : contains >
Exercise <|-- StrengthExercise
Exercise <|-- CardioExercise
AddCommand "1"--> "1"ExerciseList
MarkCommand "1"--> "1"ExerciseList
ViewCommand "1"--> "1"ExerciseList
RemoveCommand "1"--> "1"ExerciseList
FindCommand "1"--> "1"ExerciseList


@enduml