@startuml
'https://plantuml.com/sequence-diagram
skinparam classAttributeIconSize 0
hide circle

class Ui {
    + INDENT: String
    + LINE_DIVIDER: String
    + LOGO: String
    + MESSAGE_GREET: String
    + MESSAGE_BYE: String
    - scanner: Scanner
    - uiBuffer: ArrayList<String>

    + addMessage(ArrayList<String>): void
    + addMessage(ArrayList<String>, boolean): void
    + addMessage(String): void
    + addMessage(String, boolean): void
    + clearUiBuffer(): void
    + close(): void
    - currentUserSemester(int): String
    + displayDivider(): void
    + displayMessage(String): void
    + displayUi(): void
    + displayUi(boolean): void
    + displayUserPrompt(int): void
    + endMessage(): void
    + readNext(): String
    - sanitizeInput(String): String
    + startMessage(): void
}
@enduml