@startuml
!include style.puml
'https://plantuml.com/sequence-diagram

autoActivate on

'Duke -> ui: input()
'User --> ui: user input
'Duke <-- ui: user input
box Logic LOGIC_COLOR_T1
participant ":ViewCommand" as viewCommand LOGIC_COLOR
participant "<<class>>\nParser" as parser LOGIC_COLOR
end box

-> viewCommand: execute()
viewCommand -> parser: getArgumentList(arguments: String)
return argumentList: String[]
viewCommand -> parser: getClassType(argumentList: String[])
return viewType: String

alt biometrics
    ref over viewCommand: viewBiometrics

else food

else exercise

else weight

else strength

else cardio

else bmi

else maintenance

else all
    ref over viewCommand: viewAll
else invalid viewType

end
return

destroy viewCommand

@enduml