@startuml
'https://plantuml.com/sequence-diagram

!include style.puml

autoactivate on

box Logic LOGIC_COLOR_T1
participant ":ViewCommand" as viewCommand LOGIC_COLOR
end box

box Record RECORD_COLOR_T1
participant ":Biometrics" as biometrics RECORD_COLOR
participant ":WeightAndFat" as weightAndFat RECORD_COLOR
participant ":WeightAndFatList" as weightAndFatList RECORD_COLOR
end box

box Ui UI_COLOR_T1
participant ":Ui" as ui UI_COLOR
end box

activate viewCommand
group viewBiometrics
    viewCommand -> viewCommand: viewBiometrics()
    viewCommand -> biometrics: toString()
    opt at least one weight and fat record
        biometrics -> weightAndFatList: getMostRecent()
        return mostRecentRecord: WeightAndFat
        biometrics -> weightAndFat: getWeight()
        return weight: int
        biometrics -> weightAndFat: getFat()
        return fat: int
    end

    return biometrics: String
    viewCommand -> ui: output(biometrics: String)
    return
return

end

deactivate viewCommand

@enduml