@startuml
'https://plantuml.com/sequence-diagram

Actor User
"User" -> ":Duke": "view-user-loss..."
activate ":Duke"
":Duke" -> ":CommandParser": createCommand()
activate ":CommandParser"
":CommandParser" -> ":ViewUserLossCommand"**: new
activate ":ViewUserLossCommand"
return
":CommandParser" --> ":Duke"
deactivate

":Duke" -> ":ViewUserLossCommand" : executeCommand()
activate ":ViewUserLossCommand"
":ViewUserLossCommand" -> ":ViewUserLossCommand" : getArgs
activate ":ViewUserLossCommand"
":ViewUserLossCommand" -> ":TxList" : getBorrowTxByUser(user)
deactivate ":ViewUserLossCommand"
activate ":TxList"
":TxList" -> ":TxList" : new TxList()
activate ":TxList"
    loop until all items checked
        opt (given user is borrower in transaction)
            ":TxList" -> ":TxList" : increment moneyTransacted
        end
    end
deactivate ":TxList"
":TxList" --> ":ViewUserLossCommand"
deactivate ":TxList"
":ViewUserLossCommand" -> "Ui": printResponse();
deactivate ":ViewUserLossCommand"
Ui --> User:

@enduml