@startuml
!include style.puml

abstract class Media {
    +title: String
    +rating: Double
    +genre: String
    +dateWatched: Date
    +dateString: String
    +isFavourite: boolean
    +void toString()
}

class Movie {
    +Movie(title: String, rating: Double, genre: String,
    dateWatchedString: String)
    +void toString()
}
hide Movie fields

class TvShow {
    +site: String
    +dateWatched: String
    +TvShow(title: String, rating: Double, genre: String,
    dateWatchedString: String, site: String)
    +void toString()
}

skinparam groupInheritance 2
Media <|-down- Movie
Media <|-down- TvShow

@enduml