package seedu.moneygowhere.storage;

public class LocalStorageConfigurations {
    public static final String DEFAULT_CURRENCY = "SGD";
    public static final String XML_ROOT = "MoneyGoWhere";
    public static final String XML_SORTCONFIG_ELEMENT = "Sort_Configuration";
    public static final String XML_SORTCONFIG_TYPE_ATTRIBUTE = "Type";
    public static final String XML_SORTCONFIG_ORDER_ATTRIBUTE = "Order";
    public static final String XML_EXPENSE_ELEMENT = "Expense";
    public static final String XML_EXPENSE_ID_ATTRIBUTE = "Id";
    public static final String XML_EXPENSE_NAME_ELEMENT = "Name";
    public static final String XML_EXPENSE_DATETIME_ELEMENT = "Datetime";
    public static final String XML_EXPENSE_DESCRIPTION_ELEMENT = "Description";
    public static final String XML_EXPENSE_AMOUNT_ELEMENT = "Amount";
    public static final String XML_EXPENSE_AMOUNT_CURRENCY_ATTRIBUTE = "Currency";
    public static final String XML_EXPENSE_CATEGORY_ELEMENT = "Category";
    public static final String XML_EXPENSE_REMARKS_ELEMENT = "Remark";
    public static final String XML_TARGET_ELEMENT = "Target";
    public static final String XML_TARGET_ID_ATTRIBUTE = "Id";
    public static final String XML_TARGET_NAME_ELEMENT = "Name";
    public static final String XML_TARGET_DATETIME_ELEMENT = "DateTime";
    public static final String XML_TARGET_DESCRIPTION_ELEMENT = "Description";
    public static final String XML_TARGET_AMOUNT_ELEMENT = "Amount";
    public static final String XML_TARGET_CURRENT_AMOUNT_ELEMENT = "Current Amount";
    public static final String XML_TARGET_CURRENCY_ATTRIBUTE = "Currency";
    public static final String XML_RECURRING_PAYMENT_ELEMENT = "Recurring Payment";
    public static final String XML_RECURRING_PAYMENT_ID_ATTRIBUTE = "Id";
    public static final String XML_RECURRING_PAYMENT_NAME_ELEMENT = "Name";
    public static final String XML_RECURRING_PAYMENT_INTERVAL_ELEMENT = "Interval";
    public static final String XML_RECURRING_PAYMENT_DESCRIPTION_ELEMENT = "Description";
    public static final String XML_RECURRING_PAYMENT_AMOUNT_ELEMENT = "Amount";
    public static final String XML_RECURRING_PAYMENT_CURRENCY_ATTRIBUTE = "Currency";
    public static final String XML_INCOME_ELEMENT = "Income";
    public static final String XML_INCOME_ID_ATTRIBUTE = "Id";
    public static final String XML_INCOME_NAME_ELEMENT = "Name";
    public static final String XML_INCOME_DATETIME_ELEMENT = "DateTime";
    public static final String XML_INCOME_DESCRIPTION_ELEMENT = "Description";
    public static final String XML_INCOME_AMOUNT_ELEMENT = "Amount";
    public static final String XML_INCOME_CURRENCY_ATTRIBUTE = "Currency";
}
