@startuml
title Storage Diagram

skinparam classAttributeIconSize 0
hide footbox
hide circle

abstract class "{abstract}\nStorage"

class UserStorage {
    {static} - SEPARATOR: String
    - userFilePath: String
    + UserStorage(String)
    + loadData(): ArrayList<User>
    + writeData(UserList): void
    - makeUserDir(UserList): void
    + handleUserLine(String[]): User
    - getUserFromUserLine(String[]): User
    - checkCheckSumLine(User, int): void
    - checkCheckSumWhole(ArrayList<User>, int): void
}

class ItemStorage {
    {static} - SEPARATOR: String
    - itemFilePath: String
    + ItemStorage(String)
    + loadData(): ArrayList<Item>
    + writeData(ItemList): void
    - makeItemDir(ItemList): void
    + handleItemLine(String[]): Item
    - getItemFromItemLine(String[]): Item
    - checkCheckSumLine(Item, int): void
    - checkCheckSumWhole(ArrayList<Item>, int): void
}

class TransactionStorage {
    {static} - SEPARATOR: String
    - transactionFilePath: String
    + TransactionStorage(String)
    + loadData(): ArrayList<Transaction>
    + writeData(TransactionList): void
    - makeTransactionDir(TransactionList)): void
    + handleTransactionLine(String[]): Transaction
    - getTransactionFromTransactionLine(String[]): Transaction
    - checkCheckSumLine(Transaction, int): void
    - checkCheckSumWhole(ArrayList<Transaction>, int): void
}

"{abstract}\nStorage" <|-- UserStorage
"{abstract}\nStorage" <|-- ItemStorage
"{abstract}\nStorage" <|-- TransactionStorage
@enduml