@startuml
'https://plantuml.com/sequence-diagram

autonumber

Ui -> CommandParser: enter command "find-item /k Book"
CommandParser -> Command: createCommand()
Command -> itemList: FindItemCommand()
loop itemList.size() times
itemList -> itemList: iterate through list
note right
Check item.description().contains(keyword). If yes, append to returnList
end note
end
itemList -> Command: return returnList
Command -> Ui: printResponse(returnList.toString)
@enduml