@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "<color: red><<class>></color>\nCommandAddModule" as CommandAddModule LOGIC_COLOR
participant ":Nusmods" as Nusmods LOGIC_COLOR
participant "<color: red><<class>></color>\nTimetable" as Timetable LOGIC_COLOR
end box

box API MODEL_COLOR_T1
participant "NusMods API" as Api MODEL_COLOR
end box

[-> CommandAddModule : addModule(:String)
activate CommandAddModule

CommandAddModule -> Nusmods : addModuleInfo(:String, :String[])
activate Nusmods

Nusmods -> Nusmods : setURI()
activate Nusmods
Nusmods --> Nusmods : :String
deactivate Nusmods

Nusmods -> Api : send(request : HttpRequest)
activate Api
Api --> Nusmods : data:JsonNode
deactivate Api
Nusmods --> CommandAddModule : :List<Lesson>
deactivate Nusmods

CommandAddModule -> Timetable : addNewModule(:String, :String, :String, :List<Lesson>)
activate Timetable
Timetable --> CommandAddModule
deactivate Timetable

[<--CommandAddModule : responseToUser:String
deactivate CommandAddModule
@enduml