@startuml
start

:Determine overlapping
intervals of lessons
on the day;

:Re-popularize <i>rawTimetable</i>;

:Sort <i>rawTimetable</i>;

:Initialize <i>clashSlotList</i>;

:Remove non-clashed
lessons from <i>clashSlotList</i>;

:Return <i>clashSlotList</i>;

stop
@enduml 