@startuml

hide footbox

Participant ":CommandFindClient" as CommandFindClient #F4F4B6
Participant "clientList : ClientList" as ClientList #F4F4B6
Participant "client : Client" as Client #F4F4B6
Participant "ui: Ui" as Ui #F4F4B6

->CommandFindClient:execute(Ui:ui, Storage: storage, PropertyList: propertyList, \nClientList: clientList, PairingList: pairingList
activate CommandFindClient #CDEFF9

CommandFindClient->ClientList:getCurrentListSize()
activate ClientList #CDEFF9
return currentListSize

    loop i < currentListSize
        CommandFindClient->ClientList:getCurrentList()
        activate ClientList #CDEFF9
        ClientList->Client:get(int: i)
        activate Client #CDEFF9
        return client
        return currentClient

        CommandFindClient->CommandFindClient:hasQueryText(String: queryText, Client: currentClient)
        activate CommandFindClient #E2CDF9
        CommandFindClient -> Client:getClientName()
        activate Client #CDEFF9
        return clientName

        CommandFindClient -> Client:getClientContactNumber()
        activate Client #CDEFF9
        return clientContactNumber

        CommandFindClient -> Client:getClientEmail()
        activate Client #CDEFF9
        return clientEmail

        CommandFindClient -> Client:getClientBudgetPerMonth()
        activate Client #CDEFF9
        return clientBudgetPerMonth

        return hasQueryTextInClient
        opt hasQueryTextInClients
            CommandFindClient->Ui:displayOneClient(Client: currentClient, int: clientIndex)
            activate Ui #CDEFF9
            return
        end
    end
    return
@enduml