@startuml

hide footbox

participant "command:CommandAddProperty" as CommandAddProperty #FFE497
participant "propertyList:PropertyList" as PropertyList #FC9492
participant ":Property" as Property #violet
participant "ui:Ui" as Ui #lightgrey
participant "storage:Storage" as Storage #orange

->CommandAddProperty:execute(Ui, Storage, PropertyList, ClientList, PairingList)
activate CommandAddProperty #FFE497

CommandAddProperty -> PropertyList : addProperty(landlordName:String, \npropertyAddress:String, rentingPrice:String, unitType:String)
activate PropertyList #FC9492

create Property
PropertyList -> Property : Property(landlordName:String, propertyAddress:String, rentingPrice:String, unitType:String)
activate Property #violet

return
return

CommandAddProperty -> Ui : showPropertyAddedConfirmationMessage(propertyList:PropertyList)
activate Ui #lightgrey
return

CommandAddProperty -> Storage : addToPropertyFile(landlordName:String, propertyAddress:String, rentingPrice:String, unitType:String)
activate Storage #orange
return
return

@enduml