!define MONEYGOWHERE_COLOR_1 #777777

!define COMMON_COLOR_1 #FD841F

!define EXCEPTIONS_COLOR_1 #880000

!define USER_INTERFACE_COLOR_1 #5bb318
!define USER_INTERFACE_COLOR_2 #7DCE13

!define PARSER_COLOR_1 #344FA1
!define PARSER_COLOR_2 #3D84B8

!define DATA_COLOR_1 #1C0C5B
!define DATA_COLOR_2 #3D2C8D
!define DATA_COLOR_3 #4B3869
!define DATA_COLOR_4 #664E88
!define DATA_COLOR_5 #916BBF
!define DATA_COLOR_6 #C996CC

!define STORAGE_COLOR_1 #704F4F
!define STORAGE_COLOR_2 #A77979

!define LOGGER_COLOR_1 #B73E3E
!define LOGGER_COLOR_2 #DD5353

!define USER_COLOR #000000
