@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-MoneyGoWhere-Webpage/docs/diagrams/Styles.puml

skinparam noteTextAlignment left

Actor User USER_COLOR
Participant ":UserInterface" as UserInterface USER_INTERFACE_COLOR_1
Participant ":Parser" as Parser PARSER_COLOR_1
Participant ":Data" as Data DATA_COLOR_1
Participant ":Storage" as Storage STORAGE_COLOR_1

activate UserInterface USER_INTERFACE_COLOR_1

UserInterface -[USER_INTERFACE_COLOR_1]> UserInterface : getConsoleCommand()

activate UserInterface USER_INTERFACE_COLOR_1

UserInterface -[USER_INTERFACE_COLOR_1]> UserInterface : getConsoleInput()

activate UserInterface USER_INTERFACE_COLOR_1

User -[USER_COLOR]> UserInterface : User command
note right
    getConsoleInput() reads the command
    "Add-Expense -n Lunch -a 7.80"
    entered by the user
end note

UserInterface --[USER_INTERFACE_COLOR_1]> UserInterface : consoleInput: String

deactivate UserInterface

UserInterface -[USER_INTERFACE_COLOR_1]> Parser : parse(consoleInput: String)

activate Parser PARSER_COLOR_1

Parser --[PARSER_COLOR_1]> UserInterface : consoleCommandAddExpense: ConsoleCommand

deactivate Parser

UserInterface --[USER_INTERFACE_COLOR_1]> UserInterface : consoleCommand: ConsoleCommand

deactivate UserInterface

UserInterface -[USER_INTERFACE_COLOR_1]> UserInterface : runCommandAddExpense(consoleCommand: ConsoleCommandAddExpense)

activate UserInterface USER_INTERFACE_COLOR_1

UserInterface -[USER_INTERFACE_COLOR_1]> Data : addExpense(expense: Expense)

activate Data DATA_COLOR_1

Data --[DATA_COLOR_1]> UserInterface

deactivate Data

UserInterface -[USER_INTERFACE_COLOR_1]> UserInterface : printInformationalMessage(message: String)

activate UserInterface USER_INTERFACE_COLOR_1

UserInterface --[USER_INTERFACE_COLOR_1]> UserInterface

deactivate UserInterface

UserInterface -[USER_INTERFACE_COLOR_1]> Data : save()

activate Data DATA_COLOR_1

Data -[DATA_COLOR_1]> Storage : saveToFile(expenses: ArrayList<Expenses>)

activate Storage STORAGE_COLOR_1

Storage --[STORAGE_COLOR_1]> Data

deactivate Storage

Data --[DATA_COLOR_1]> UserInterface

deactivate Data

UserInterface --[USER_INTERFACE_COLOR_1]> UserInterface

deactivate UserInterface
@enduml
