@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-MoneyGoWhere-Webpage/docs/diagrams/Styles.puml

package Exceptions {
    Class MoneyGoWhereException EXCEPTIONS_COLOR_1

    package Exceptions.Data {
        Class Hidden1 #ffffff
    }
    package Exceptions.Parser {
        Class Hidden2 #ffffff
    }
    package Exceptions.Storage {
        Class Hidden3 #ffffff
    }
}

Exceptions.Data --up-|> MoneyGoWhereException
Exceptions.Parser --up-|> MoneyGoWhereException
Exceptions.Storage --up-|> MoneyGoWhereException
@enduml
