@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-MoneyGoWhere-Webpage/docs/diagrams/Styles.puml

package UserInterface {
    Class ConsoleInterface USER_INTERFACE_COLOR_1
}

package Parser {
    Class Hidden1 #ffffff
}

package Data {
    Class Hidden2 #ffffff
}

package Logger {
    Class Hidden3 #ffffff
}

ConsoleInterface -down-> Parser
ConsoleInterface -down-> Data
ConsoleInterface -down-> Logger
@enduml
