@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-Webpage/docs/diagrams/Styles.puml

package UserInterface {
    Class "        ConsoleInterface        " as ConsoleInterface USER_INTERFACE_COLOR_1
}

package Parser {
    Class ConsoleParser PARSER_COLOR_1
}

package Data {
    Class ExpenseManager DATA_COLOR_1
    Class IncomeManager DATA_COLOR_2
    Class RecurringPaymentManager DATA_COLOR_3
    Class TargetManager DATA_COLOR_4
}

package Apis {
    Class CurrencyApiManager DATA_COLOR_6
}

package Logger {
    Class LocalLogger LOGGER_COLOR_1
}

ExpenseManager -down[hidden]-> RecurringPaymentManager
IncomeManager -down[hidden]-> TargetManager

ConsoleInterface -left-> "1" ConsoleParser
ConsoleInterface -down-> "1" ExpenseManager
ConsoleInterface -down-> "1" IncomeManager
ConsoleInterface -down-> "1" RecurringPaymentManager
ConsoleInterface -down-> "1" TargetManager
ConsoleInterface -down-> "1" CurrencyApiManager
ConsoleInterface -right-> "1" LocalLogger
@enduml
