@startuml

hide footbox

activate ": DatabaseStorage"

-> ": DatabaseStorage" : loadDatabase()

": DatabaseStorage" -> ": DatabaseStorage" : readFile(DATABASE_FILE_PATH)
activate ": DatabaseStorage"

loop hasNextLine
    ": DatabaseStorage" -> ": DatabaseStorage" : readDatabaseLine(line)
    activate ": DatabaseStorage"

    ": DatabaseStorage" -> ": DatabaseParser" : parseDatabaseLine(line)
    activate ": DatabaseParser"
    ": DatabaseParser" --> ": DatabaseStorage" : lineData : String[]
    deactivate ": DatabaseParser"

    ": DatabaseStorage" -> ": Database" : addUniversity(newUniversity)
    activate ": Database"
    deactivate ": Database"

    ": DatabaseStorage" -> ": Database" : addModuleMapping(newModuleMapping)
    activate ": Database"
    deactivate ": Database"

    deactivate ": DatabaseStorage"
end

deactivate ": DatabaseStorage"

deactivate ": DatabaseStorage"

@enduml