@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-Webpage/docs/diagrams/Styles.puml

skinparam sequenceReferenceBackgroundColor #ffffff

Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1
Participant "targetManager:TargetManager" as targetManager DATA_COLOR_4
Participant "<<class>>\nLocalStorage" as LocalStorage STORAGE_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

opt consoleCommand instanceof ConsoleCommandEditTarget
    consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : \lrunCommandEditTarget(\n\tconsoleCommand:ConsoleCommandEditTarget\n)
    activate consoleInterface USER_INTERFACE_COLOR_1

    consoleInterface -[USER_INTERFACE_COLOR_1]> targetManager : getTarget(targetIndex:int)
    activate targetManager DATA_COLOR_4

    targetManager --[DATA_COLOR_4]> consoleInterface : oldTarget:Target
    deactivate targetManager

    consoleInterface -[USER_INTERFACE_COLOR_1]> targetManager : \leditTarget(\n\ttargetIndex:int,\n\tnewTarget:Target\n)
    activate targetManager DATA_COLOR_4

    targetManager --[DATA_COLOR_4]> consoleInterface
    deactivate targetManager

    ref over consoleInterface: print target

    ref over consoleInterface, targetManager, LocalStorage: save data

    consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface
    deactivate consoleInterface
end

deactivate consoleInterface
@enduml
