@startuml
!include Styles.puml

skinparam noteTextAlignment left

mainframe sd print income

Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1
Participant "localLogger:Logger" as localLogger LOGGER_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : convertIncomeToConsoleString(income:Income)
activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface : incomeStr:String
deactivate consoleInterface

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : printInformationalMessage(incomeStr:String)
activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface -[USER_INTERFACE_COLOR_1]> localLogger : logInformationalMessage(incomeStr:String)
activate localLogger LOGGER_COLOR_1

localLogger --[LOGGER_COLOR_1]> consoleInterface
deactivate localLogger

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface
deactivate consoleInterface
@enduml
