@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-MoneyGoWhere-Webpage/docs/diagrams/Styles.puml

skinparam noteTextAlignment left

Actor User USER_COLOR
Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1
Participant "<<class>>\nParser" as Parser PARSER_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : getConsoleCommand()
activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : getConsoleInput()
activate consoleInterface USER_INTERFACE_COLOR_1

User -[USER_COLOR]> consoleInterface : User command
note right
    getConsoleInput() reads the
    command entered by the user
end note

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface : consoleInput:String
deactivate consoleInterface

consoleInterface -[USER_INTERFACE_COLOR_1]> Parser : parse(consoleInput:String)
activate Parser PARSER_COLOR_1

note right
    Parser calls the corresponding parse command
    function based on consoleInput.
end note

Parser --[PARSER_COLOR_1]> consoleInterface : consoleCommand:ConsoleCommand
deactivate Parser

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface : consoleCommand:ConsoleCommand
deactivate consoleInterface
@enduml
