@startuml
!include https://raw.githubusercontent.com/xzynos/tp/branch-Webpage/docs/diagrams/Styles.puml

skinparam noteTextAlignment left

mainframe sd Print Income

Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : convertIncomeToConsoleString(income:Income)
activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface : incomeStr:String
deactivate consoleInterface

consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : printInformationalMessage(incomeStr:String)
activate consoleInterface USER_INTERFACE_COLOR_1

consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface
deactivate consoleInterface
@enduml
