@startuml
!include Styles.puml

skinparam sequenceReferenceBackgroundColor #ffffff

Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1
Participant "expenseManager:ExpenseManager" as expenseManager DATA_COLOR_1
Participant "<<class>>\nLocalStorage" as LocalStorage STORAGE_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

opt consoleCommand instanceof ConsoleCommandSortExpense
    consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : \lrunCommandSortExpense(\n\tconsoleCommand:ConsoleCommandSortExpense\n)
    activate consoleInterface USER_INTERFACE_COLOR_1

    consoleInterface -[USER_INTERFACE_COLOR_1]> expenseManager : updateSortExpenses()
    activate expenseManager DATA_COLOR_1

    expenseManager -[DATA_COLOR_1]> expenseManager : sortExpenses()
    activate expenseManager DATA_COLOR_1

    expenseManager -[DATA_COLOR_1]> expenseManager : getComparator()
    activate expenseManager DATA_COLOR_1

    expenseManager --[DATA_COLOR_1]> expenseManager :
    deactivate expenseManager DATA_COLOR_1

    expenseManager --[DATA_COLOR_1]> expenseManager :
    deactivate expenseManager

    expenseManager --[DATA_COLOR_1]> consoleInterface

    deactivate expenseManager

    ref over consoleInterface, expenseManager, LocalStorage: save data

    consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface
    deactivate consoleInterface
end

deactivate consoleInterface
@enduml
