@startuml
!include Styles.puml

skinparam sequenceReferenceBackgroundColor #ffffff

Participant "consoleInterface:ConsoleInterface" as consoleInterface USER_INTERFACE_COLOR_1
Participant "target\n:Target" as target DATA_COLOR_4
Participant "targetManager\n:targetManager" as targetManager DATA_COLOR_4
Participant "<<class>>\nLocalStorage" as LocalStorage STORAGE_COLOR_1

activate consoleInterface USER_INTERFACE_COLOR_1

opt consoleCommand instanceof ConsoleCommandAddTarget
    consoleInterface -[USER_INTERFACE_COLOR_1]> consoleInterface : \lrunCommandAddTarget(\n\tconsoleCommand:ConsoleCommandAddTarget\n)
    activate consoleInterface USER_INTERFACE_COLOR_1

    create target

    consoleInterface -[USER_INTERFACE_COLOR_1]> target : create
    activate target DATA_COLOR_4

    target --[DATA_COLOR_4]> consoleInterface
    deactivate target

    consoleInterface -[USER_INTERFACE_COLOR_1]> targetManager : addTarget(target:Target)
    activate targetManager DATA_COLOR_4

    targetManager --[DATA_COLOR_4]> consoleInterface
    deactivate targetManager

    ref over consoleInterface: print target

    ref over consoleInterface, targetManager, LocalStorage: save data

    consoleInterface --[USER_INTERFACE_COLOR_1]> consoleInterface
    deactivate consoleInterface
end

deactivate consoleInterface
@enduml
