@startuml
skinparam Style strictuml


package parser as pkg{
class Parser
class ParserUtils
class RecipeFileParser
class TitleFileParser
note "attributes and methods omitted to avoid clutter" as N1
}

TitleFileParser o.- ParserUtils



TitleFileParser .- N1
RecipeFileParser .- N1


class Parser{
    +{static}parseCommand()
    -parseAddCommand()
    -parseEditCommand()
    -parseDeleteCommand()
    -parseExitCommand()
    -parseFindCommand()
    -parseHelpCommand()
    -parseListCommand()
    -parseViewCommand()
}



package command {
Abstract Command {
    +commandResult:execute()
}
Class AddCommand
Class EditCommand
Class DeleteCommand
Class ExitCommand
Class FindCommand
Class HelpCommand
Class ListCommand
Class ViewCommand
Class InvalidCommand
}
Parser *-right-> command
AddCommand -up-|> Command
EditCommand -up-|> Command
DeleteCommand -up-|> Command
ExitCommand -up-|> Command
FindCommand -down-|> Command
HelpCommand -l-> Command
ListCommand -down-|> Command
ViewCommand -down-|> Command
InvalidCommand -down-|> Command

Ui -u-> Parser: input

@enduml