@startuml
hide circle
skinparam classAttributeIconSize 0

class PrescriptionList {
+ isEmpty() : boolean
+ add(ui:UI, patientId:String, medicine:String, dosage:String, timeInterval:String) : void
+ add(ui:UI, patientId:String, medicine:String, dosage:String, timeInterval:String, isActive:boolean) : void
+ viewAll(ui:UI) : void
+ viewPatientPrescription(ui:UI, patientId:String) : void
+ viewActivePatientPrescription(ui:UI, patientId:String) : void
+ edit(ui:UI, prescriptionNumber:int, medicine:String, dosage:String, timeInterval:String) : void
+ activatePrescription(ui:UI, prescriptionNumber:String) : void
+ deactivatePrescription(ui:UI, prescriptionNumber:String): void
- hasPatientPrescription(patientId:String) : boolean
- hasActivePatientPrescription(patientId) : boolean
}

class Prescription {
- patientId: String
- medicine : String
- timeInterval : String
- dosage : String
- isActive : Boolean
}

class UI {
+ printMessageAndObject(object:String, message:String, index:int, type:type) : void
+ printNoPrescriptionMessage() : void
+ printViewAllPrescriptionsMessage() : void
+ printPrescriptionWithIndex(index:int, prescription:Prescription) : void
+ printNoMatchingActivePrescriptionMessage() : void
+ printViewAllActivePrescriptionsMessage() : void
+ printIndexOutOfRangeErrorMessage() : void
}

PrescriptionList "1" *-down-> "*" Prescription
PrescriptionList .down.> UI
@enduml