@startuml
hide footbox
skinparam sequenceReferenceBackgroundColor #White

box
participant ":PrescriptionList" as A
participant ":Prescription" as B
participant "prescriptionList\n:ArrayList<Prescription>" as C
end box

participant "ui:UI" as D

[-> A : add(ui, patientId, \nmedicine, dosage, timeInterval)
activate A

create B
A -> B : new Prescription(ui, patientId, medicine, dosage, timeInterval)
activate B
B --> A : prescription:Prescription
deactivate B

A -> C : contains(prescription)
activate C
return hasDuplicate:boolean

alt hasDuplicate == false
    A -> C : add(prescription)
    activate C
    return

    ref over A, B, C
        get prescriptionString and index of prescription
    end

    A -> D : printMessageAndObject(prescriptionString, \nUI.ADD_PRESCRIPTION, index, UI.PRESCRIPTION)
    activate D
    return

else else
    ref over A, B, C
        get prescriptionString and index of prescription
    end

    A -> D : printMessageAndObject(prescriptionString, \nUI.DUPLICATE_PRESCRIPTION_MESSAGE, index, UI.PRESCRIPTION)
    activate D
    return
end

return

@enduml