@startuml
!include <office/Concepts/globe_internet>
!include <office/Concepts/documents>
!include <office/Users/user>
!include https://raw.githubusercontent.com/xzynos/tp/branch-MoneyGoWhere-Webpage/docs/diagrams/Styles.puml

Package " "<<Rectangle>>{
    Class MoneyGoWhere MONEYGOWHERE_COLOR_1

    Class Common COMMON_COLOR_1

    Class UserInterface USER_INTERFACE_COLOR_1

    Class Parser PARSER_COLOR_1
    Class Command PARSER_COLOR_2

    Class Data DATA_COLOR_1

    Class Apis DATA_COLOR_6

    Class Storage STORAGE_COLOR_1

    Class Logger LOGGER_COLOR_1
}

Class "<$user>" as User USER_INTERFACE_COLOR_2
Class "<$documents>" as DataFile STORAGE_COLOR_2
Class "<$documents>" as LogFile LOGGER_COLOR_2

MoneyGoWhere -down-> UserInterface

User -down-> UserInterface

UserInterface -right-> Parser
UserInterface -down-> Data
UserInterface -left-> Logger

Logger .left.> LogFile

Parser -down-> Command

Data -down-> Storage
Data -down-> Apis

Storage .left.> DataFile
@enduml
