@startuml
'https://plantuml.com/sequence-diagram

->Storage:openPreviousState()
alt Has previous state
    Storage -> Storage: loadPreviousState()
    Storage -> Link: parseLink(link,state)
    Link --> Storage: previousState
    Storage -> State: previousState
    Storage -> UI: Display success message
else No previous state
    Storage -> UI : Display error message
end

@enduml