@startuml
hide footbox

-> ":TimetableManager" : printTimetable()
activate ":TimetableManager"
":TimetableManager" -> ":Timetable" : getTimetable()
activate ":Timetable"
":TimetableManager" <-- ":Timetable" : timetable
deactivate ":Timetable"
opt timetable exists
    ":TimetableManager" -> ":Ui" : printTimetable()
    activate ":Ui"
    ":TimetableManager" <-- ":Ui"
    deactivate ":Ui"
end
<-- ":TimetableManager"
deactivate ":TimetableManager"
@enduml