@startuml
hide class fields
hide class methods

package Recipe {
class RecipeList
class Recipe
class Ingredient
}

package Ui {
class Ui
class AddMode
class Editor
}

class Storage

Ui ..> CommandResult

AddMode --> Recipe
AddMode --> Ingredient
RecipeList *-right-> Recipe
Recipe *-right-> Ingredient
Editor .down-> Storage

@enduml