@startuml
'https://plantuml.com/sequence-diagram

hide circle
skinparam classAttributeIconSize 0

class Module {
}

class InvalidUniversityException {
}

class InvalidModuleException{
}

class UserModuleMapping {
    + nusModule:Module
    + puModule:Module
    - comment: String
    + UserModuleMapping(puCode:String, puTitle:String, nusCode:String, nusTitle:String,
                        nusCredit:String, puCredit:String, puName:String, puCountry:String)
    + toString()
}

class Ui {
}

class UserModuleMappingList {
    - modules:ArrayList<UserModuleMapping>
    + UserModuleMappingList()
    + findModuleByCode(input:UserModuleMapping)
    + addModule(input:UserModuleMapping)
    + addModule(input:UserModuleMapping, isFromDatabase:boolean)
    + displayAll()
    + deleteModuleByPuCode(input:String)
    + getModuleByPuCode(input:String)
    + deleteModule(index:int)
    + updateModule(puCode:String, nusCode:String, updates:String)
    + updateComment(moduleCode:String, comment:String)
    + deleteComment(moduleCode:String)
    + findModuleByTitle(keyword:String)
}

UserModuleMapping " *  " --> "0..2" Module :> Maps
UserModuleMappingList " 1 " o--> " * " UserModuleMapping
UserModuleMappingList .> Ui
UserModuleMapping --> InvalidModuleException :<<throws>>
UserModuleMapping --> InvalidUniversityException :<<throws>>

@enduml