@startuml
hide circle
skinparam classAttributeIconSize 0

class UserStorage {
    {static} - UNI_STORAGE_FILE_PATH : String
    {static} - TIMETABLE_STORAGE_FILE_PATH : String

    {static} + saveFile(textToAdd : String) : void
    {static} + loadFile() : void
}

class IOException {

}

class UserStorageParser {
    {static} + convertUniversityListIntoFileContent(uniList : UserUniversityListManager) : String
    {static} + convertFileContentIntoUniversityList(fileContent : String) : HashMap<String, UserUniversityList>
    {static} + convertTimetableIntoFileContent(timetableManager TimetableManager) : String
    {static} + convertFileContentIntoTimetable(fileContent : String) : TimetableManager
    {static} + getSavedLists() : UserUniversityListManager
    {static} + storeCreatedLists(userUniversityListManager : UserUniversityListManager) : void
    {static} + getSavedTimetables(): TimetableManager
    {static} + storeTimetable(timetableManager TimetableManager) : void
}

class InvalidUserStorageFileException {

}

UserStorage --> IOException : <<throws>>
UserStorage "1" --> "1" UserStorageParser
UserStorageParser --> InvalidUserStorageFileException : << throws>>
@enduml