@startuml
'https://plantuml.com/sequence-diagram

-> ":UserUniversityListManager" : createList(input)
activate ":UserUniversityListManager"

":UserUniversityListManager" -> ":UserUniversityListManager" : containsKey((input)
activate ":UserUniversityListManager"
return : boolean

alt school already exists

else new school list
    ":UserUniversityListManager" -> ":UserUniversityList" **: new
    activate ":UserUniversityList"
    return ":UserUniversityList"
    ":UserUniversityListManager" -> ":UserUniversityListManager" : put(input, newList)
    activate ":UserUniversityListManager"

    ":UserUniversityListManager" -> ":Ui" : printPuListCreatedAcknowledgement(input)
    activate ":Ui"
    return

    return

end
return
deactivate ":UserUniversityListManager"

-> ":UserUniversityListManager" : deleteList(input)
activate ":UserUniversityListManager"

":UserUniversityListManager" -> ":UserUniversityListManager" : containsKey((input)
activate ":UserUniversityListManager"
return : boolean

alt inputSchool exists
    ":UserUniversityListManager" -> ":UserUniversityListManager" : remove(inputSchool)
    activate ":UserUniversityListManager"

    ":UserUniversityListManager" -> ":Ui" : printPuListDeletedAcknowledgement(inputSchool)
    activate ":Ui"
    return
else inputSchool does not exist
end

return
deactivate ":UserUniversityListManager"

-> ":UserUniversityListManager" : addModule(inputSchool, inputModule)
activate ":UserUniversityListManager"
":UserUniversityListManager" -> ":UserUniversityListManager" : containsKey(inputSchool)
activate ":UserUniversityListManager"
return : boolean

alt inputSchool exists
    ":UserUniversityListManager" -> ":UserUniversityListManager" : getUserUniversityList(inputSchool)
    activate ":UserUniversityListManager"
    return : ":UserUniversityList"
    ":UserUniversityListManager" -> ":UserUniversityList" : addModule(inputModule)
    activate ":UserUniversityList"

    ":UserUniversityList" -> ":UserUniversityList" : addModule(input)
    activate ":UserUniversityList"
    ":UserUniversityList" -> ":UserUniversityList" : findModuleByCode(input)
    activate ":UserUniversityList"
    return : boolean
    alt module already exists
    else new module
        ":UserUniversityList" -> ":UserUniversityList" : add(input)
        activate ":UserUniversityList"

        ":UserUniversityList" -> ":Ui" : printModuleAddedAcknowledgement(input)
        activate ":Ui"
        ":UserUniversityList" <-- ":Ui"
        deactivate ":Ui"
        return
    end
    ":UserUniversityList" <-- ":UserUniversityList"
    deactivate ":UserUniversityList"
    ":UserUniversityListManager" <-- ":UserUniversityList"
    deactivate ":UserUniversityList"

else inputSchool does not exist

end
return
deactivate ":UserUniversityListManager"

-> ":UserUniversityListManager" : deleteModule(inputSchool, puCode)
activate ":UserUniversityListManager"
":UserUniversityListManager" -> ":UserUniversityListManager" : containsKey(inputSchool)
activate ":UserUniversityListManager"
return : boolean
alt inputSchool exists
    ":UserUniversityListManager" -> ":UserUniversityListManager" : getUserUniversityList(inputSchool)
    activate ":UserUniversityListManager"
    return : ":UserUniversityList"

    ":UserUniversityListManager" -> ":UserUniversityList" : getMyModules()
    activate ":UserUniversityList"


    ":UserUniversityList" -> ":UserUniversityList" : getModuleByPuCode(puCode)
    activate ":UserUniversityList"
    return : ":UserModuleMapping"

    return deletedModule : ":UserModuleMapping"

    ":UserUniversityListManager" -> ":UserDeletedModules" : addToDeletedModule(deletedModule)
    activate ":UserDeletedModules"
    ":UserDeletedModules" -> ":UserDeletedModules" : size()
    activate ":UserDeletedModules"
    return : int
        alt size == 5
        ":UserDeletedModules" -> ":UserDeletedModules" : removeLast()
        activate ":UserDeletedModules"
        return
        else size < 5
        ":UserDeletedModules" -> ":UserDeletedModules" : addFirst(deletedModule)
        activate ":UserDeletedModules"
        return
    end
    return

    ":UserUniversityListManager" -> ":UserUniversityListManager" : getUserUniversityList(inputSchool)
    activate ":UserUniversityListManager"
    return : ":UserUniversityList"

        ":UserUniversityListManager" -> ":UserUniversityList" : deleteModuleByPuCode(puCode)
        activate ":UserUniversityList"

        ":UserUniversityList" -> ":UserUniversityList" : deleteModuleByPuCode(puCode)
        activate ":UserUniversityList"
        loop for every module
        ":UserUniversityList" -> ":UserUniversityList" : get(index)
        activate ":UserUniversityList"
        return ":UserModuleMapping"
        ":UserUniversityList" -> ":UserModuleMapping" : getPuCode()
        activate ":UserModuleMapping"
        return puCode : String
        ":UserUniversityList" -> ":UserUniversityList" : equals(puCode)
        activate ":UserUniversityList"
        return : boolean
        opt module code matches
        ":UserUniversityList" -> ":UserUniversityList" : deleteModule(index)
        activate ":UserUniversityList"
        return
        end

    end

    return

    return


else inputSchool does not exist
end
return
deactivate ":UserUniversityListManager"

@enduml