@startuml
hide circle

skinparam classAttributeIconSize 0
class BuildManager {
    -builds: HashMap<String, Build>

    +BuildManager()
    +addBuild(): void
    +deleteBuild(): void
    +getBuild(): Build
    +getBuilds(): HashMap<String, Build>
    +findBuilds() : void
    +filterBuilds() : void
}

class Build {
}

BuildManager --- Build
@enduml