@startuml
'https://plantuml.com/sequence-diagram

autonumber

activate Build
Build -> LinkedHashMap2D: Initialize

activate LinkedHashMap2D

Build -> LinkedHashMap2D: addComponent(type, component)

LinkedHashMap2D -> LinkedHashMap2D: addElement(type, component.getName(), component)

Build -> LinkedHashMap2D: deleteComponent(type, component)

LinkedHashMap2D -> LinkedHashMap2D: removeElement(type, component.getName())


@enduml