@startuml
'https://plantuml.com/object-diagram

object StoryBook
object TextBook
object ChineseBook
object Shoes
object Glasses

object ItemList

ItemList o-- StoryBook
ItemList o-- TextBook
ItemList o-- ChineseBook
ItemList o-- Glasses
ItemList o-- Shoes



@enduml
