@startuml
'https://plantuml.com/class-diagram

hide class fields
hide class methods

package Recipe {
class RecipeList
class Recipe
class Ingredient
}

Storage -up-> Ui
Storage -down-> Recipe
Storage -down-> Ingredient
Storage -down-> RecipeList

Recipe *-right-> Ingredient
Storage ..> Recipe
@enduml