'https://plantuml.com/sequence-diagram

@startuml
activate Duke
[-> Duke: User input
Duke -> Parser: parse(input)
activate Parser
Parser -> Parser: specificCase(commandWord, content)
activate Parser
Parser -> Mcs: new Mcs(content)
activate Mcs
return c: Mcs
return c: Mcs
return c: Mcs
deactivate Parser
Duke -> Mcs: c.execute(moduleList)
activate Mcs
activate ModuleList
Mcs -> ModuleList: mc(semester)
deactivate Mcs
ModuleList -> ModuleList: check mod.getSemesterTaken().matches(semester)
activate ModuleList
return mcsCount: integer
ModuleList -> UI: mcMessage(semester, mcsCount)
activate UI
deactivate UI

@enduml