@startuml
!include Style.puml
abstract class "Command"{
    + execute() : void {abstract}
}

abstract class "FindCommand"{
    + keyword : String
    + getMandatoryTags() : String[]
    + execute() : void
    + findTransactions() : void
}



FindCommand -up-|> "Command"



@enduml