@startuml
!include Style.puml

Participant ":Duke" as duke
Participant ":CommandParser" as commandParser
Participant ":ParameterParser" as parameterParser
Participant "command:FindCommand" as command
Participant "transactions:TransactionList" as transactions
Participant "ui:Ui" as ui
actor User

-> duke
activate duke
duke -> commandParser:parse("find k/bus_fare")
    activate commandParser
    create command
    commandParser -> command:new
        activate command
    return command:FindCommand
    commandParser -> parameterParser:parse
        parameterParser -> command:set keyword
        note left: Minimal\nnotation
    return command:FindCommand

duke -> command:execute(transactions, ui, storage)
    activate command
    command -> command: findTransactions(transactions, ui, keyword)
        activate command
        command -> transactions:findTransactions(keyword:String)
        activate transactions
        return transactionsList:String
        alt transactionsList isEmpty
            command -> ui:showInfoMessage(message)
            activate ui
                ui -> User
            return
        else else
            command -> ui:showList(transactionsList, message)
            activate ui
                ui -> User
            return
        end
    return


return
@enduml