@startuml
!include Style.puml


Participant ":Duke" as duke
Participant ":Storage" as storage
Participant "storedTransactions:\nTransactionList" as storedList
Participant ":Budget" as budget
Participant "transactionList:\nTransactionList" as transactionList
Participant "transactionList:\nTransactionList" as emptyTransactionList



activate duke
    create storage
    duke -> storage:Storage()
        activate storage
        create storedList
        storage -> storedList:TransactionList()
            activate storedList
        return :TransactionList
    return :Storage

    duke -> storage:initializeFile()
    activate storage
        storage -> budget:setBudget()
        activate budget
        return
        loop Until End-of-File
            alt isExpense
                storage -> storedList:addExpenseDuringStorage()
                activate storedList
                return
            else isIncome
                storage -> storedList:addIncomeDuringStorage()
                activate storedList
                return
            end
        end

    return stored:TransactionList

    destroy storedList
    note over storedList
        Due to UML tool limitation, the lifeline is not shown ended after the red cross
    end note

    alt Successful initialization
        create transactionList
        duke -> transactionList:TransactionList(stored)
        activate transactionList
        return transactionList:TransactionList
    else File initialization failure
        create emptyTransactionList
        duke -> emptyTransactionList:TransactionList()
        activate emptyTransactionList
        return transactionList:TransactionList

    end
@enduml